### ISSUE TITLE
Flights view

### ISSUE THREAD

**Issue by HRuvalcabaP** [Brightcoders-Bootcamps/kata-04-reservacion-de-vuelos-team-01-nov#5]
# REQUIREMENTS
in this screen we'll need show all flights that the user was realized and a button to add new flights

# DESIGN
![image](https://user-images.githubusercontent.com/50897282/104227153-93bf5f80-540e-11eb-8b19-9b7e53e53164.png)

# Acceptance Criteria
List all required acceptance criteria
- [ ] A button to add new flights
- [ ] Show all flights of the user
- [ ] Respect the suggested design

**Comment by sebasdrk17** [comment]
Para hacer la lista ocupas escribir fuera de [], seria asi:
- [] a button to add new flights
- [] Show ....
